# Generated by Django 3.2.4 on 2021-06-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
