# Generated by Django 3.2.4 on 2021-07-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20210702_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
