# Generated by Django 3.2.4 on 2021-07-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_auto_20210702_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='stock',
        ),
    ]
