# Generated by Django 3.2.4 on 2021-07-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_remove_car_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(),
        ),
    ]
