# Generated by Django 3.2.4 on 2021-07-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_setting_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='address',
        ),
    ]
