# Generated by Django 3.2.4 on 2021-07-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20210702_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='returndate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rezdate',
            field=models.DateTimeField(),
        ),
    ]
