# Generated by Django 3.2.4 on 2021-07-02 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20210702_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='returndate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rezdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
