# Generated by Django 3.2.4 on 2021-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20210702_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='returndate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rezdate',
            field=models.DateField(),
        ),
    ]
