# Generated by Django 3.2.4 on 2021-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20210702_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(),
        ),
    ]
