# Generated by Django 3.2.4 on 2021-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_reservation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
